nba_project:
  outputs:
    dev:
      account: lv27483.us-east-2.aws
      database: NBA_STATS_ANALYTICS
      password: *******
      role: ACCOUNTADMIN
      schema: NBA_STATS
      threads: 1
      type: snowflake
      user: badreeshshetty
      warehouse: NBA_STATS_WAREHOUSE
  target: dev
