WITH transformed_player_stats AS (
    SELECT
        PLAYER_ID,
        PLAYER,
        TEAM,
        GP,
        MIN,
        FGM,
        FGA,
        FG3M,
        FG3A,
        FTM,
        FTA,
        OREB,
        DREB,
        REB,
        AST,
        STL,
        BLK,
        TOV,
        PF,
        PTS,
        PTS / GP AS PPG,
        AST / GP AS APG,
        REB / GP AS RPG,
        BLK / GP AS BPG,
        STL / GP AS SPG,
        FGM / FGA AS FG_PERCENT,
        FG3M / FG3A AS FG3_PERCENT,
        FTM / FTA AS FT_PERCENT
    FROM {{ ref('transformed_player_stats') }}
),
transformed_top_100_players_stats AS (
    SELECT
        PLAYER_ID,
        RANK,
        PLAYER,
        TEAM,
        GP,
        MIN,
        FGM,
        FGA,
        FG3M,
        FG3A,
        FTM,
        FTA,
        OREB,
        DREB,
        REB,
        AST,
        STL,
        BLK,
        TOV,
        PF,
        PTS,
        PTS / GP AS PPG,
        AST / GP AS APG,
        REB / GP AS RPG,
        BLK / GP AS BPG,
        STL / GP AS SPG,
        FGM / FGA AS FG_PERCENT,
        FG3M / FG3A AS FG3_PERCENT,
        FTM / FTA AS FT_PERCENT
    FROM {{ ref('transformed_top_100_players_stats') }}
),
joined_stats AS (
    SELECT
        p.PLAYER_ID,
        p.PLAYER,
        p.TEAM,
        p.GP,
        p.MIN,
        p.FGM,
        p.FGA,
        p.FG3M,
        p.FG3A,
        p.FTM,
        p.FTA,
        p.OREB,
        p.DREB,
        p.REB,
        p.AST,
        p.STL,
        p.BLK,
        p.TOV,
        p.PF,
        p.PTS,
        p.PPG,
        p.APG,
        p.RPG,
        p.BPG,
        p.SPG,
        p.FG_PERCENT,
        p.FG3_PERCENT,
        p.FT_PERCENT,
        t.RANK AS TOP_100_RANK
    FROM transformed_player_stats p
    INNER JOIN transformed_top_100_players_stats t
    ON p.PLAYER_ID = t.PLAYER_ID
)
SELECT
    PLAYER_ID,
    PLAYER,
    TEAM,
    GP,
    MIN,
    FGM,
    FGA,
    FG3M,
    FG3A,
    FTM,
    FTA,
    OREB,
    DREB,
    REB,
    AST,
    STL,
    BLK,
    TOV,
    PF,
    PTS,
    PPG,
    APG,
    RPG,
    BPG,
    SPG,
    FG_PERCENT,
    FG3_PERCENT,
    FT_PERCENT,
    TOP_100_RANK
FROM joined_stats
