
-- CREATE WAREHOUSE NBA_STATS_WAREHOUSE WITH WAREHOUSE_SIZE='x-small';
-- CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;
-- CREATE SCHEMA IF NOT EXISTS NBA_STATS_ANALYTICS.NBA_STATS;

DESC INTEGRATION SNOW_S3;


CREATE STAGE IF NOT EXISTS SNOW_S3_STAGE
STORAGE_INTEGRATION = SNOW_S3
URL = 's3://nba-stats-players/';
-- FILE_FORMAT = CSV_FORMAT;


LIST @SNOW_S3_STAGE;


SELECT * FROM NBA_NEWS;

SELECT * FROM NBA_SCORES;

SELECT * FROM PLAYER_STATS;

SELECT * FROM TOP_100_PLAYERS_STATS;



--- FOR DBT TRANSFORMED DATA ---
--- When connected to NBA_STATS_ANALYTICS.NBA_STATS_DBT_NBA_STATS ---
SELECT * FROM TRANSFORMED_NBA_NEWS;

SELECT * FROM TRANSFORMED_PLAYER_STATS;

SELECT * FROM STAGING_NBA_SCORES;

SELECT * FROM TRANSFORMED_TOP_100_PLAYERS_STATS;

SELECT PLAYER, GP, MIN, TOP_100_RANK FROM TOP_100_2024_ALL_TIME;









